### ISSUE TITLE
Library does not work with Rails 5.1 due to use of before_filter

### ISSUE THREAD

**Issue by kevinburkeomg** [pelle/oauth-plugin#157]
If you try to include this library with Rails 5.1, you get the following error:

```
Failure/Error: include Oauth::Controllers::ConsumerController

NoMethodError:
  undefined method `before_filter' for OAuthConsumersController:Class
  Did you mean?  before_action
# ./vendor/bundle/ruby/2.4.0/gems/oauth-plugin-0.5.1/lib/oauth/controllers/consumer_controller.rb:6:in `block in included'
# ./vendor/bundle/ruby/2.4.0/gems/oauth-plugin-0.5.1/lib/oauth/controllers/consumer_controller.rb:5:in `class_eval'
# ./vendor/bundle/ruby/2.4.0/gems/oauth-plugin-0.5.1/lib/oauth/controllers/consumer_controller.rb:5:in `included'
# ./app/controllers/oauth_consumers_controller.rb:3:in `include'
# ./app/controllers/oauth_consumers_controller.rb:3:in `<class:OAuthConsumersController>'
# ./app/controllers/oauth_consumers_controller.rb:2:in `<top (required)>'
```

`before_filter` was removed in Rails 5.1, so this library isn't compatible. It looks like #156 will fix the issue.

**Comment by JorgeLAB** [comment]
I believe t gem is no longer sustained. 

t last commit, 
<img width="905" alt="image" src="https://github.com/pelle/oauth-plugin/assets/41846128/34d29408-d011-4091-9b22-15209b957e64">
